language: python
python:
  - "3.8"
install:
  - pip3 install selenium
  - pip3 install pytest
  - pip3 install ddt
  - pip3 install allure-pytest
  - pip3 install pyyaml
  - pip3 install requests
  - pip3 install webdriver_manager
script:  pytest tests/ndtv_test/ndtv_tests.py --browser headless --alluredir=reports -v -s
#pytest tests/test_suite_demo.py --browser chrome --alluredir=reports --env staging
#pytest tests/test_suite_demo.py --browser headless --alluredir=reports --env staging