language: python
python:
  - "3.8"
services:
    - docker
before_install:
  docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-chrome:latest

install:
  - pip3 install selenium
  - pip3 install pytest
  - pip3 install allure-pytest
  - pip3 install pyyaml
  - pip3 install requests
  - pip3 install webdriver_manager
  - pip3 install pytest-ordering

script:  pytest tests/skf_test.py -v -s --browser="docker-chrome" --alluredir="reports"
