language: python
python:
  - "3.8"
install:
  - pip3 install selenium
  - pip3 install pytest
  - pip3 install ddt
  - pip3 install allure-pytest
  - pip3 install yaml
script: pytest tests/test_suite_demo.py --browser chrome --alluredir=reports