language: python
python:
  - "3.8"
install:
  - pip3 install selenium
  - pip3 install pytest
  - pip3 install allure-pytest
  - pip3 install pyyaml
  - pip3 install requests
  - pip3 install webdriver_manager
  - pip3 install pytest-ordering
script:  pytest tests/flipkart_test.py -v -s --browser="headless" --alluredir="reports"
